### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by gbdavidx** [petrasonic/Xandem-Bridge#3]
Do you still use xandem…? Can it detect more then one person?

**Comment by petrasonic** [comment]
As I recall, yes this was tested with two people and was working to some degree. There were some issues with people who were stationary (sitting on the couch). This was tested when xandem was still in early release. At the time they promised updates to help resolve those issues but, I got tired or waiting and abandoned this project. I assume they have more updates by now?

**Comment by gbdavidx** [comment]
Do you not use anything for presence detection or home automation? They
don’t seem to be very responsive

**Comment by petrasonic** [comment]
I just use PIR (Passive Infrared) sensors now. It's not perfect, but it's the best solution I have come across so far.

**Comment by rafale77** [comment]
I am still using it. It is really a motion detection system so if nothing is moving... indeed it won't see anything. Not too different from PIR actually. I like the benefit that it sees beyond walls and furniture and it is able to give an approximate location. I use it as part of my home automation system and it can detect more than 1 person at a time, showing it on the screen. I haven't really used anything beyond a single alarm for motion detection for the entire system though and if I could get more granularity, I could do a lot more with it. The downside for me is the multiple floors support and the limited range. It does interfere somewhat with the 2.4GHz spectrum as well.

**Comment by gbdavidx** [comment]
@Rafale77,  how did you get your hands on one? were you an early adopter?

**Comment by rafale77** [comment]
Yes I got mine through crowdfunding.

**Comment by gbdavidx** [comment]
Last question, how fast are you able to see movement in your automation
software, I use home assistant. If I’m moving around in my office, how
quickly could home assistant pick up my movement?

**Comment by rafale77** [comment]
It is instantaneous... I am using the scene/automation on the xandem hub to send an http call to my automation system so it is event based, not polling based. I am not using any bridge.

**Comment by gbdavidx** [comment]
That’s dope. Thanks. Now only if xandem would return emails so I can buy
one!
